embedding_size: 64
feat_embed_dim: 64

n_layers: [2] 
dropout: [0.3] 
reg_weight: [0.01] 
cl_weight: 2.0
learning_rate: [0.001] # [0.01, 0.001, 0.0001, 0.00001]
cl_weight2: [0.1, 0.001, 0.005] # [0.0001, 0.0005, 0.00005, 0.001]

use_neg_sampling: False

hyper_parameters: ["n_layers","learning_rate", "reg_weight", "dropout", "cl_weight2"]
